# Generated by Django 3.2.19 on 2024-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_debate_stance', '0002_alter_aistancesubject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aistancesubject',
            name='description',
            field=models.TextField(blank=True, help_text='In addition to the title, you can insert an optional explanatory text (max. 350 char.). This field is only shown in the participation if it is filled out.', max_length=500, verbose_name='Description'),
        ),
    ]
