# Generated by Django 3.2.15 on 2023-01-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance', models.CharField(choices=[('FAVOR', 'favor'), ('AGAINST', 'against')], max_length=50)),
                ('comment_text', models.TextField(max_length=4000)),
            ],
        ),
    ]
