# Generated by Django 3.2.19 on 2023-08-10 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('a4_candy_stance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stance',
            name='comment_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stance',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stance',
            name='creator',
            field=models.TextField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stance',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
