# Generated by Django 3.2.19 on 2023-09-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('a4_candy_stance', '0002_auto_20230810_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('user_stance', models.CharField(choices=[('FAVOR', 'favor'), ('AGAINST', 'against')], max_length=50)),
                ('creator', models.TextField(max_length=200)),
                ('creator_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
