# Generated by Django 3.2.19 on 2023-09-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_stance', '0003_userstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstance',
            name='creator_id',
            field=models.CharField(max_length=500),
        ),
    ]
