# Generated by Django 3.2.19 on 2023-10-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_stance', '0006_alter_userstance_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstance',
            name='questionbox_shown',
            field=models.BooleanField(default=False),
        ),
    ]
