# Generated by Django 3.2.19 on 2023-10-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_stance', '0009_auto_20231011_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstance',
            name='user_stance',
            field=models.CharField(default='', max_length=50),
        ),
    ]
