# Generated by Django 3.2.19 on 2023-10-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_stance', '0010_alter_userstance_user_stance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstance',
            name='creator_id',
            field=models.CharField(max_length=500),
        ),
    ]
