# Generated by Django 3.2.19 on 2024-07-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_stance', '0012_usedstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stance',
            name='is_blocked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='stance',
            name='is_censored',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='stance',
            name='is_removed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
