# Generated by Django 3.2.19 on 2024-07-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_stance', '0013_auto_20240701_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstance',
            name='guideline_shown',
            field=models.BooleanField(default=False),
        ),
    ]
