# Generated by Django 3.2.7 on 2021-11-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_classifications', '0003_alter_classification_choices_to_lowercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiclassification',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userclassification',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
