# Generated by Django 3.2.12 on 2022-04-05 13:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_classifications', '0004_add_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiclassification',
            name='classification',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('OFFENSIVE', 'offensive'), ('ENGAGING', 'engaging'), ('FACTCLAIMING', 'fact claiming'), ('OTHER', 'other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userclassification',
            name='classification',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('OFFENSIVE', 'offensive'), ('ENGAGING', 'engaging'), ('FACTCLAIMING', 'fact claiming'), ('OTHER', 'other')], max_length=50),
        ),
    ]
