# Generated by Django 3.2.12 on 2022-04-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_classifications', '0005_make_classification_multiselect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiclassification',
            old_name='classification',
            new_name='classifications',
        ),
        migrations.RenameField(
            model_name='userclassification',
            old_name='classification',
            new_name='classifications',
        ),
    ]
