# Generated by Django 3.2.13 on 2022-04-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a4comments', '0009_comment_is_blocked'),
        ('a4_candy_classifications', '0006_rename_classification_to_classifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiclassification',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_classifications', to='a4comments.comment'),
        ),
        migrations.AlterField(
            model_name='userclassification',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_classifications', to='a4comments.comment'),
        ),
    ]
