# Generated by Django 3.2.19 on 2023-07-25 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_classifications', '0008_make_classifications_char_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiclassification',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='aiclassification',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='userclassification',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='userclassification',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified'),
        ),
    ]
