# Generated by Django 3.2.19 on 2024-03-05 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4modules', '0007_verbose_name_created_modified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a4_candy_debate_quality_random', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AIQualitySubject',
            new_name='QualityRandomSubject',
        ),
    ]
