# Generated by Django 3.2.19 on 2024-04-26 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a4modules', '0007_verbose_name_created_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('is_other_choice', models.BooleanField(default=False)),
                ('weight', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['weight', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='a4modules.item')),
            ],
            options={
                'abstract': False,
            },
            bases=('a4modules.item',),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='a4pollsreact.choice')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherVote',
            fields=[
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='other_vote', serialize=False, to='a4pollsreact.vote')),
                ('answer', models.CharField(max_length=250, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=250, verbose_name='Explanation')),
                ('weight', models.SmallIntegerField()),
                ('multiple_choice', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='a4pollsreact.poll')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='a4pollsreact.question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified')),
                ('answer', models.CharField(max_length=750, verbose_name='Answer')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='a4pollsreact.question')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('question', 'creator')},
            },
        ),
    ]
