# Generated by Django 3.2.19 on 2024-04-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_debate', '0003_increase_description_char_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, help_text='In addition to the title, you can insert an optional explanatory text (max. 350 char.). This field is only shown in the participation if it is filled out.', max_length=450, verbose_name='Description'),
        ),
    ]
