# Generated by Django 3.2.15 on 2022-12-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_debateai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisubject',
            name='description',
            field=models.CharField(blank=True, help_text='In addition to the title, you can insert an optional explanatory text (max. 350 char.). This field is only shown in the participation if it is filled out.', max_length=350, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='aisubject',
            name='name',
            field=models.CharField(help_text='max 120 characters', max_length=120, verbose_name='Title'),
        ),
    ]
