# Generated by Django 3.2.19 on 2024-04-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_users', '0007_userlogins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bilendi_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='bilendi id'),
        ),
    ]
