# Generated by Django 3.2.19 on 2024-04-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_users', '0008_user_bilendi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogins',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
