# Generated by Django 3.2.19 on 2024-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_users', '0009_alter_userlogins_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogins',
            name='email_intern',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
