# Generated by Django 3.2.19 on 2024-04-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_users', '0010_alter_user_username'),
        ('a4_candy_users', '0010_userlogins_email_intern'),
    ]

    operations = [
    ]
