# Generated by Django 3.2.19 on 2024-01-03 13:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a4modules', '0007_verbose_name_created_modified'),
        ('a4_candy_debate_stance_random', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AIStanceSubject',
            new_name='StanceRandomSubject',
        ),
    ]
