# Generated by Django 3.2.15 on 2023-04-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('ENHANCING', 'enhancing'), ('NOT ENHANCING', 'notenhancing')], max_length=50)),
                ('comment_text', models.TextField(max_length=4000)),
            ],
        ),
    ]
