# Generated by Django 3.2.19 on 2023-08-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_quality', '0002_auto_20230810_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='prediction',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quality',
            name='quality',
            field=models.CharField(choices=[('high', 'high'), ('low', 'low')], max_length=4),
        ),
    ]
