# Generated by Django 3.2.19 on 2023-08-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_quality', '0003_auto_20230821_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='quality',
            field=models.TextField(choices=[('high', 'high'), ('low', 'low')], max_length=4),
        ),
    ]
