# Generated by Django 3.2.19 on 2023-12-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_quality', '0005_alter_quality_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='labels',
            field=models.TextField(default='Labels', max_length=25),
            preserve_default=False,
        ),
    ]
