# Generated by Django 3.2.19 on 2024-01-11 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_quality', '0006_quality_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='quality',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified'),
        ),
    ]
