# Generated by Django 3.2.19 on 2024-01-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_quality', '0007_auto_20240111_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality',
            options={'ordering': ('created',), 'verbose_name': 'Quality', 'verbose_name_plural': 'Qualities'},
        ),
    ]
