# Generated by Django 3.2.19 on 2024-07-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_quality', '0011_userquality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquality',
            old_name='questionbox_shown',
            new_name='guideline_shown',
        ),
    ]
